Update for Firefox extension
FunixProductions/Twitch-Extensions pull request #3
Opened 2023-02-22 17:09 UTC by iGameCreep

Petite update pour que l'extension soit fonctionnelle sur Firefox, le fichier manifest.json a été modifié de façon a ce qu'il soit accepté par Firefox et d'autres petits détails par ci par la.
Problème non réglé : dans le popup, le bouton violet qui mène sur le live apparait sur les données contenant le nombre de viewers et la manette avec comme texte "Hors ligne". Il ne devrait pas être la je suppose...

2023-02-22 17:16 UTC, iGameCreep commented
Problème du bouton violet réglé dans les 2 derniers commits !

2023-02-24 11:46 UTC, FunixG requested changes
Tu as fait un duplicata du code source de l'app chrome, ce qui n'est pas une bonne pratique. Tu dois essayer de voir s'il est possible de fusionner le manifest de chrome et de firefox et d'avoir une seule codebase pour les deux extensions.

Car si on modifie le code source de chrome on doit copier coller sur firefox ce qui peut donner des erreurs sur certaines mises en prod.
Moins de copier coller = moins de problèmes :D

2023-02-24 11:46 UTC, FunixG commented on README.md
> -# extention_twitch
On ne modifie pas le README, c'est le fichier de description du projet.
Seul le créateur / chef de projet s'occupe de ça

2023-02-24 11:46 UTC, FunixG commented on browser-addons - firefox/manifest.json
> +{
Je pense qu'il serait judicieux de regarder s'il n'est pas possible de fusionner le manifest de chrome et le manifest de firefox.
Faire un duplicata dans un repo du code source html css js n'est pas forcément une bonne idée. Si on modifie le code source de chrome il faudra copier coller le code sur firefox ce qui n'est pas une bonne pratique.

2023-02-24 11:48 UTC, iGameCreep commented on README.md
> -# extention_twitch
Ok, je vais voir pour arranger ca, et my bad pour le readme. Merci d'avoir quand même regardé !

2023-02-24 11:50 UTC, FunixG requested changes
J'ai oublié de mettre en viewed, pense bien a check pour ne pas dupliquer le code

2023-03-21 21:14 UTC, closed without merging